//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.Web.TCModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string InitialName { get; set; }
        public string CompanyEmail { get; set; }
        public string EmailId { get; set; }
        public string Passwd { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<bool> ShowBirthDayAnnouncement { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string LocationId { get; set; }
        public string GroupId { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public string Extension { get; set; }
        public string DirectDial { get; set; }
        public string Mobile { get; set; }
        public string SecrateContactNumber { get; set; }
        public string ProfilePicture { get; set; }
        public string EContactName { get; set; }
        public string ERelationship { get; set; }
        public string EPhone { get; set; }
        public string EEmail { get; set; }
        public string AuthyId { get; set; }
        public string UserToken { get; set; }
        public string UserActiveStatus { get; set; }
        public Nullable<bool> isCloser { get; set; }
        public Nullable<bool> isGhostUser { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<bool> isDeleteLock { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isProfileCompleted { get; set; }
        public Nullable<bool> isApproved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<bool> isRejected { get; set; }
        public Nullable<System.DateTime> RejectedDate { get; set; }
        public Nullable<int> RejectedBy { get; set; }
    }
}
